### ISSUE TITLE
setSimpleData 默认选中第一行？

### ISSUE THREAD

**Issue by yushuifeng** [iuap-design/kero#1]
实际使用过程中默认选中第一行的场景几乎没有，而目前如果想不选中第一行还需要再增加参数（unselect）？这个设计好像反过来了

**Comment by LiuYueKai** [comment]
之前主要考虑的是erp中主子表和左树右表的情况比较多，因此设计成了默认选中第一行，这样会把子表的数据显示出来，省去了主动选择了。

**Comment by yushuifeng** [comment]
这种主要还是在左右主子表的情况下回用到吧？但在erp里这种结构的也不是很多，单表的结构还是占比很大的，这种情况下都需要去处理为默认不选中。

**Comment by LiuYueKai** [comment]
为了保证代码的兼容后续会增加setUnSelectSimpleData方法

**Comment by LiuYueKai** [comment]
目前通过下面的方式来实现不默认选中第一行。
setSimpleData(data,{unSelect:true})
