### ISSUE TITLE
dataTable输入框改变值后，getValue获取到的值是修改前的值

### ISSUE THREAD

**Issue by SoDanTengAndYou** [iuap-design/kero#11]
#### 描述这个问题:
dataTable输入框改变值后，getValue获取到的值还是原先修改前的值

#### 当前的行为:
dataTable输入框改变值（小改动）后，无法识别最新的值（也无法触发valueChange），getValue获取到的值还是原先修改前的值。
编辑后的值：
![image](https://cloud.githubusercontent.com/assets/24285229/21480367/3b0696fa-cb97-11e6-927d-0bd80c6983f6.png)
 getValue获取到的值：
![image](https://cloud.githubusercontent.com/assets/24285229/21480386/717116a2-cb97-11e6-892d-e8b339ba198e.png)

#### 期望的行为:
只要有改动，就要能获取改动后的值，且能触发valueChange事件

**Comment by whizbz11** [comment]
内容已经修改，下个版本升级
