### ISSUE TITLE
checkbox 状态无法正常toggle

### ISSUE THREAD

**Issue by Anryliu** [iuap-design/kero#15]
### Bug 报告

- __Package version(s)__: (neoui-kero v3.2.1)

#### 描述这个问题:

 <label class="u-checkbox   u-checkbox-info c-checkbox-info  " style="height: 28px;"
                                                               data-bind="click: datatable.toggleAllSelect.bind(datatable), css:{'is-checked': datatable.allSelected()}"> 如果我清空了 datatable(new u.DataTable()),上面的 checkbox 需要点击两次才可以改变状态

#### 当前的行为:

 清空了 datatable(new u.DataTable()),上面的 checkbox 需要点击两次才可以改变状态 

#### 期望的行为:

 点击可以正常toggle 状态 ,无需多点记一次

**Comment by HuYuee** [comment]
你说的清空了datatable，是指做了什么操作。方不方便留下其他联系方式，这样更方便交流。

**Comment by GuoYongfeng** [comment]
issue 提供的信息不完整，先 close 掉。
