### ISSUE TITLE
DataTable后台部分给个文档吧

### ISSUE THREAD

**Issue by yushuifeng** [iuap-design/kero#2]
后台的一些注解的用法，datatable的一些操作方法，给出一个开发文档吧。

**Comment by GuoYongfeng** [comment]
@yushuifeng 好的，目前正在梳理....

**Comment by GuoYongfeng** [comment]
你好，请访问地址：http://design.yyuap.com/dist/pages/kero/dataTableUseBackend.html

另外，后续后端datatable相关的实践不再推荐，建议找我沟通具体的技术架构，谢谢。
