### ISSUE TITLE
官网敢不敢只用kero与neoui做

### ISSUE THREAD

**Issue by Glimis** [iuap-design/kero#3]
rt-。-
这样才好抄嘛。。
而且感觉连官网都要依赖其他组件
那一定是kero和neoui太不完善了-。-

**Comment by LiuYueKai** [comment]
多谢提出宝贵意见，目前框架确实不够完善，我已添加future标签，后续待框架完善之后对官网进行重构。

**Comment by GuoYongfeng** [comment]
你好，目前design的官网基于neoui实现；即将上线的开源新官网tinper.org也在使用tinper平台提供的技术产品开发。
