### ISSUE TITLE
金额转换

### ISSUE THREAD

**Issue by Glimis** [iuap-design/kero#4]
http://design.yyuap.com/dist/pages/kero/currency_ex.html

内容可以为负的假设可以理解
第一个.或者更多的.不允许输入也可以理解
但是输入字母却很正常,并且提示输入为非数字与.是两种处理方式,是一个什么交互方案?

**Comment by LiuYueKai** [comment]
经测试字母是不能输入的，其他不太合适的地方后续会逐步完善。

**Comment by Glimis** [comment]
不是转换后，是转换前 字母可以输,转换金额后字母被干掉  
但问题是.与字母的交互方式不一样

**Comment by LiuYueKai** [comment]
明白了，后续完善

**Comment by LiuYueKai** [comment]
目前已经控制不允许输入字母
@Glimis
