### ISSUE TITLE
时间组件

### ISSUE THREAD

**Issue by Glimis** [iuap-design/kero#5]
http://design.yyuap.com/dist/pages/kero/ex_year.html

在输入框内输入-20160,
20160年,假设我能理解
但是-20160年算什么鬼
输入字母提示NaN,算法绝对有问题啊

http://design.yyuap.com/dist/pages/kero/ex_month.html
输入框内随意输入字母

其他输入组件基本都可以输入数字..只有少数不可以

**Comment by LiuYueKai** [comment]
多谢提出的宝贵意见，后续我们会做相应修改以完善框架。

**Comment by LiuYueKai** [comment]
年份和月份的输入已经控制了只能输入数字了。
@Glimis
