### ISSUE TITLE
分页求自动处理

### ISSUE THREAD

**Issue by Glimis** [iuap-design/kero#6]
http://design.yyuap.com/dist/pages/kero/ex_pagination.html

分页已经包含data信息,那么每次`pageChange`应该都可以直接处理吧
可以在架构中直接处理不
这样可以少些n个函数

**Comment by LiuYueKai** [comment]
请详细描述一下，不太明白具体是什么问题。

**Comment by Glimis** [comment]
分页控件

``` html
<div id='pagination' class='u-pagination'  u-meta='{"type":"pagination","data":"listData"}'>
 </div>
```

其中data中的数据listData(datatable),包含了total,pagesize等相关的属性  
即便写pageChange函数,本身也是去主动操作一遍相关的data,比如listData  
我的意思是框架直接去处理这种公共逻辑

**Comment by LiuYueKai** [comment]
恩。知道是什么意思了，待重构结束之后会优先处理此问题。

**Comment by GuoYongfeng** [comment]
感谢 @Glimis  同学的反馈，期待后续能够通过pr参与一起贡献代码。

**Comment by LiuYueKai** [comment]
目前已经通过datatable自动处理分页。
