### ISSUE TITLE
为什么不用ko组件的方式处理js组件?

### ISSUE THREAD

**Issue by Glimis** [iuap-design/kero#7]
kero依赖于ko,又依赖于neoui
为什么不用ko组件的方式,去处理neoui?
这样,在写业务的时候就不用处理成两种风格了

**Comment by LiuYueKai** [comment]
在框架设计时neoui的写法想要更公用一些，并没有想要将neoui和ko进行关联。后续neoui会处理为react组件，而ko也可能替换为其他类库，整体来说这2部分是单独的，只不过通过kero关联在了一起。

**Comment by Glimis** [comment]
好吧,用kero关联,那就是不能使用ko自带的viewmodel方式咯  
举个栗子  
我的查询条件就一个,时间  
如果要使用时间空间,就必须得写个datatable...对吧  
好蛋疼的操作方式,那datatable可以改成复用的方式吗?比如通过DatatableManage函数统一注册与获取,以及如果我确定这就是一个form表单(获取第一条数据),能不能不要返回数组

**Comment by LiuYueKai** [comment]
neoui是可以单独使用的，不关联kero也是可以的，也可以通过css类来创建组件。

http://design.yyuap.com/dist/pages/neoui/index.html  下的说明就是针对不关联kero的。

参照demo：

http://design.yyuap.com/dist/pages/plugins/date.html

这就是不关联kero的。

**Comment by Glimis** [comment]
问题是我们已经使用了ko啊  
如果使用了ko,然后直接使用neoui,那就相当于业务逻辑使用了两派操作(jq,mvvm)  
这完全就是两类框架缺点的集合体好吗-。-  
举个栗子  
如果我只加入neoui   
- 我得 加入初始化函数(我是spa)
- 我得定义/获取选择器(我得操作组件)
- 我不能通过mvvm的方式修改组件的信息,包括meta数据与html数据(结构可能已经被组件强制修改,mvvm不一定能监控的了)
- 基于上一条,因为没有文档,在解决时,可能会的通过选择器定义事件过于全局,可能会产生的选择器事件污染(选择器太大众),多次绑定(没有描述作用域)
- ....

可能遇见的问题,比使用kero还要蛋疼的

**Comment by LiuYueKai** [comment]
确实，目前的应用方式对于你这种情况确实不太友好，稍后考虑一下再回复你。

**Comment by LiuYueKai** [comment]
暂不支持
