### ISSUE TITLE
在data Table 的u-meta中增加编辑前事件

### ISSUE THREAD

**Issue by SoDanTengAndYou** [iuap-design/kero#9]
在data Table 的u-meta中增加编辑前事件，谢谢哈~~~ 0.0 ~~~

**Comment by LiuYueKai** [comment]
datatable增加监听：beforeValueCHange。
grid增加监听：onBeforeEditFun以及onBeforeValueChange

**Comment by SoDanTengAndYou** [comment]
刚刚试了一下，复选框的beforeValueChange事件，会将复选框的勾选状态改变再执行。现在需要在编辑前事件中判断是否符合条件，如果不符合，不允许取消勾选。且不是对整个datatable所有字段改变都需要执行这个事件，而是针对一个 field，应该怎么做呢。

**Comment by SoDanTengAndYou** [comment]
刚刚试了一下，复选框的beforeValueChange事件，会将复选框的勾选状态改变再执行。现在需要在编辑前事件中判断是否符合条件，如果不符合，不允许取消勾选。且不是对整个datatable所有字段改变都需要执行这个事件，而是针对一个  @field，应该怎么做呢。 @LiuYueKai

**Comment by SoDanTengAndYou** [comment]
提供了最新补丁后，经过测试，在IE下并没有生效（谷歌可以）~~~

**Comment by whizbz11** [comment]
平台提供的beforeEdit这个功能支持ie10，是因为象屿代码中获取元素判断问题，使用event.srcElement||event.target获取吧
